# Generated by Django 5.1.3 on 2024-12-14 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=200)),
                ('job', models.CharField(max_length=100)),
                ('income', models.CharField(max_length=100)),
                ('foodExpense', models.CharField(max_length=100)),
                ('educationExpense', models.CharField(max_length=100)),
                ('healthExpense', models.CharField(max_length=100)),
                ('transportationTaxExpense', models.CharField(max_length=100)),
                ('pbbTaxExpense', models.CharField(max_length=100)),
                ('electricityExpense', models.CharField(max_length=100)),
                ('financialServiceAccess', models.BooleanField(default=False)),
                ('healthServiceAccess', models.BooleanField(default=False)),
                ('governmentAssistance', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
